# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%image_directory%'
    filesystems:
        local:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem